on: [pull_request]

jobs:
  linux-self-hosted:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v7

      - name: Write kubeconfig
        env:
          KUBECFGDATA: ${{ secrets.KUBECONF_APPDEV_COMMON_STAGING }}
        run: |
          echo "$KUBECFGDATA" | base64 --decode > .kube_config.yml

      - uses: ./
        with:
          release: test-self-hosted
          namespace: default
          chart: tests/chart
          values: |
            config:
              foo: bar
          values-files: |
            tests/v1.yaml
            tests/v2.yaml
        env:
            KUBECONFIG: .kube_config.yml
